#!/usr/bin/env python3
"""Regenerates the hero-widget waveform vectors (widget_wave_1..8.xml).

Matches the concept art: many thin baseline-aligned bars in a clustered
envelope (tall groups separated by near-baseline dots), animating as a
travelling wave across 8 ViewFlipper frames. Run from android/app/:

    python3 tool/gen_widget_wave.py
"""
import math
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent.parent / (
    "android/app/src/main/res/drawable"
)

VIEWPORT_W = 110
VIEWPORT_H = 24
BASELINE_Y = 22
BAR_COUNT = 36
BAR_X0 = 2.5
BAR_SPACING = (VIEWPORT_W - 2 * BAR_X0) / (BAR_COUNT - 1)
STROKE_WIDTH = 2
FRAME_COUNT = 8
FLOOR_H = 2.0
PEAK_H = 18.0
CLUSTER_CENTERS = (6, 15, 26)
CLUSTER_SIGMAS = (3.2, 2.4, 3.6)

GRADIENT_STOPS = ("#F533C8", "#A93CF2", "#6F4BF5")


def lerp_color(t: float) -> str:
    """Linear-interpolate a 3-stop gradient at t in [0, 1]."""
    t = min(max(t, 0.0), 1.0)
    segment = min(int(t * 2), 1)
    local_t = t * 2 - segment
    c0 = GRADIENT_STOPS[segment]
    c1 = GRADIENT_STOPS[segment + 1]
    r0, g0, b0 = int(c0[1:3], 16), int(c0[3:5], 16), int(c0[5:7], 16)
    r1, g1, b1 = int(c1[1:3], 16), int(c1[3:5], 16), int(c1[5:7], 16)
    r = round(r0 + (r1 - r0) * local_t)
    g = round(g0 + (g1 - g0) * local_t)
    b = round(b0 + (b1 - b0) * local_t)
    return f"#{r:02X}{g:02X}{b:02X}"


def gaussian(i: float, center: float, sigma: float) -> float:
    return math.exp(-(((i - center) / sigma) ** 2))


def envelope(i: int) -> float:
    peak = max(gaussian(i, c, s) for c, s in zip(CLUSTER_CENTERS, CLUSTER_SIGMAS))
    return FLOOR_H + PEAK_H * peak


def bar_height(i: int, frame: int) -> float:
    phase = 2 * math.pi * (i / 6 + frame / FRAME_COUNT)
    modulation = 0.55 + 0.45 * math.sin(phase)
    return min(max(envelope(i) * modulation, 0.6), 20.0)


def render_frame(frame: int) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f"<!-- Music-waveform frame {frame + 1}/{FRAME_COUNT}. {BAR_COUNT} thin "
        "baseline-aligned bars spanning the 4x1 hero widget's text column, in "
        "a clustered envelope (tall groups separated by near-baseline dots) "
        "matching the concept art. Cycling the 8 frames in a ViewFlipper reads "
        "as a smooth travelling wave. Bars are tinted along the heerr "
        "magenta->violet gradient (left->right). RemoteViews can't host a "
        "custom view, so animation = flipping vectors. Generated by "
        "tool/gen_widget_wave.py — do not hand-edit. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{VIEWPORT_W}dp"',
        f'    android:height="{VIEWPORT_H}dp"',
        f'    android:viewportWidth="{VIEWPORT_W}"',
        f'    android:viewportHeight="{VIEWPORT_H}">',
    ]
    for i in range(BAR_COUNT):
        x = BAR_X0 + i * BAR_SPACING
        h = bar_height(i, frame)
        top = BASELINE_Y - h
        color = lerp_color(i / (BAR_COUNT - 1))
        lines.append(
            f'    <path android:strokeColor="{color}" android:strokeWidth="{STROKE_WIDTH}"\n'
            f'        android:strokeLineCap="round" '
            f'android:pathData="M{x:.1f},{top:.1f} L{x:.1f},{BASELINE_Y}" />'
        )
    lines.append("</vector>")
    return "\n".join(lines) + "\n"


def main() -> None:
    for frame in range(FRAME_COUNT):
        out_path = OUT_DIR / f"widget_wave_{frame + 1}.xml"
        out_path.write_text(render_frame(frame))
        print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
